### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zjedwin** [nerdrax/pwp-capstones#1]
Thanks for your submission. Here are a few comments on your code.

### `get_average_rating` implementation in `User` class
I have two comments here. First, you should divide the number of books which have ratings that are not `None`. You currently have
```python
return sum([rating for rating in self.books.values() if rating is not None]) / len(self.books)
```
You want to divide by the length of the list in the numerator. Because of this, it may be best to define that list as a variable first.
Finally, be sure that the value that you're dividing by is not zero.

### `add_rating` implementation in `Book` class
Note that if you pass the number zero to this method
```python
if not rating or rating < 0 or rating > 4:
    return "Invalid Rating"
else:
    self.ratings.append(rating)
```
you will return "Invalid Rating". This is because `not 0 == True`. I would recommend writing
```python
if rating in range(5):
    self.ratings.append(rating)
else:
    return "Invalid Rating"
```
This works because `range(5)` contains values `0, 1, 2, 3, 4`.

### `get_average_rating` implementation in `Book` class
Note that on the following line
```python
return sum([rating for rating in self.ratings]) / len(self.ratings)
```
`[rating for rating in self.ratings]` is the same thing as `self.ratings`. So you should simply write `sum(self.ratings)`. Also, check that the values you're dividing by are not zero.

### General comments about `TomeRater` class
You continue to redefine the variable `isbns`. Simply define it in inside `__init__`.
Note also that the implementation of the following methods `most_read_book` `highest_rated_book`, and `most_positive_user` are very similar. This is because they're performing the same essential operation: get the largest of a property from a given set. This is a telltale sign of a place to insert a function which you may then call multiple times. You do a good job of this by calling the `max` function but you can do better by combining `max` and list comprehension aspects of your implementations into a single function. Similarly with your `get_n...` methods.

### `add_user` implementation in `TomeRater` class
Note that your first check does not adequately check for valid emails. For example, under this check, ".com@" is a valid email. To develop a robust checker, look into regular expressions in Python.

**Comment by nerdrax** [comment]
Thank you for the feedback, duly noted.
